CREATE TABLE IF NOT EXISTS face_profiles (
  face_profile_id SERIAL PRIMARY KEY,
  student_id INT NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
  compreface_subject_id VARCHAR(255) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
